import { Table, TableHeader, TableRow, TableHead, TableData } from "./styles";

export default function List() {
    return (
        <Table>
            <thead>
                <TableHeader>
                    <TableHead>Tarefa</TableHead>
                    <TableHead>Descrição</TableHead>
                    <TableHead>Data</TableHead>
                </TableHeader>
            </thead>
            <tbody>
                <TableRow>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                </TableRow><TableRow>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                </TableRow><TableRow>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                </TableRow><TableRow>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                </TableRow><TableRow>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                </TableRow><TableRow>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                </TableRow><TableRow>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                </TableRow><TableRow>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                    <TableData>AAA</TableData>
                </TableRow>
            </tbody>
        </Table>
    )
}
